#Copyright Florian Goujeon 2021 - 2026.
#Distributed under the Boost Software License, Version 1.0.
#(See accompanying file LICENSE or copy at
#https://www.boost.org/LICENSE_1_0.txt)
#Official repository: https://github.com/fgoujeon/maki

version: 1.0.{build}

image:
  - Visual Studio 2022

environment:
  matrix:
    - PLATFORM: Win32
      VCPKG_ARCH: x86-windows
      CXX_STANDARD: 17
      MAKI_BUILD_TESTS_20: 0
      CONFIGURATION: Debug

    - PLATFORM: x64
      VCPKG_ARCH: x64-windows
      CXX_STANDARD: 17
      MAKI_BUILD_TESTS_20: 0
      CONFIGURATION: Release

    - PLATFORM: x64
      VCPKG_ARCH: x64-windows
      CXX_STANDARD: 20
      MAKI_BUILD_TESTS_20: 1
      CONFIGURATION: Release

install:
  - vcpkg install catch2:%VCPKG_ARCH%
  - vcpkg install boost-cobalt:%VCPKG_ARCH%

build_script:
  - cmake ^
      -S . ^
      -B build ^
      -A %PLATFORM% ^
      -DCMAKE_CXX_STANDARD=%CXX_STANDARD% ^
      -DCMAKE_CXX_STANDARD_REQUIRED=ON ^
      -DMAKI_BUILD_TESTS=1 ^
      -DMAKI_BUILD_TESTS_20=%MAKI_BUILD_TESTS_20% ^
      -DMAKI_BUILD_EXAMPLES=1 ^
      -DCMAKE_CXX_FLAGS="/EHsc /W4 /permissive- /WX" ^
      -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake
  - cmake --build build --config %CONFIGURATION%

test_script:
  - ctest --test-dir build --verbose -C %CONFIGURATION% --output-on-failure
